apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: proxy-rolebinding
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: datapipeline-operator
    app.kubernetes.io/part-of: datapipeline-operator
    app.kubernetes.io/managed-by: kustomize
  name: {{ .Values.operator.namePrefix }}proxy-rolebinding
  namespace: {{ .Values.operator.namePrefix }}system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.operator.namePrefix }}proxy-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.operator.namePrefix }}controller-manager
  namespace: {{ .Values.operator.namePrefix }}system
