apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: proxy-role
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: datapipeline-operator
    app.kubernetes.io/part-of: datapipeline-operator
    app.kubernetes.io/managed-by: kustomize
  name: {{ .Values.operator.namePrefix }}proxy-role
  namespace: {{ .Values.operator.namePrefix }}system
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
