apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: datapipeline-operator
    app.kubernetes.io/part-of: datapipeline-operator
    app.kubernetes.io/managed-by: kustomize
  name: {{ .Values.operator.namePrefix }}controller-manager
  namespace: {{ .Values.operator.namePrefix }}system
