apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/component: discovery-handler
    app.kubernetes.io/instance: akri
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: akri-udev-discovery
    app.kubernetes.io/part-of: akri
    app.kubernetes.io/version: 0.12.20
    helm.sh/chart: akri-0.12.20
  name: akri-udev-discovery-daemonset
  namespace: default
  resourceVersion: "5637"
  uid: 1997eefe-7e85-412d-9541-c3e683a08ff5
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: akri
      app.kubernetes.io/name: akri-udev-discovery
      app.kubernetes.io/part-of: akri
  template:
    metadata:
      labels:
        app.kubernetes.io/component: discovery-handler
        app.kubernetes.io/instance: akri
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: akri-udev-discovery
        app.kubernetes.io/part-of: akri
        app.kubernetes.io/version: 0.12.20
        helm.sh/chart: akri-0.12.20
    spec:
      containers:
      - env:
        - name: DISCOVERY_HANDLERS_DIRECTORY
          value: /var/lib/akri
        image: ghcr.io/project-akri/akri/udev-discovery:v0.12.20-dev
        imagePullPolicy: IfNotPresent
        name: akri-udev-discovery
        resources:
          limits:
            cpu: 24m
            memory: 24Mi
          requests:
            cpu: 10m
            memory: 11Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/akri
          name: discovery-handlers
        - mountPath: /run/udev
          name: devices
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/lib/akri
          type: ""
        name: discovery-handlers
      - hostPath:
          path: /run/udev
          type: ""
        name: devices
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
